import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { io, Socket } from 'socket.io-client';
import { api, setToken } from './lib/api';
import type { Activity, Role, Task, User } from './types';
import './styles.css';

const socketUrl = import.meta.env.VITE_SOCKET_URL || 'http://localhost:4000';
const labels: Record<string,string> = { TODO:'To Do', IN_PROGRESS:'In Progress', IN_REVIEW:'In Review', DONE:'Done', LOW:'Low', MEDIUM:'Medium', HIGH:'High', CRITICAL:'Critical' };

function Login({ onLogin }: { onLogin: (u: User) => void }) {
  const [email,setEmail] = useState('admin@velozity.local'); const [password,setPassword] = useState('Password123!'); const [error,setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); try { const r=await api.post('/auth/login',{email,password}); setToken(r.data.accessToken); onLogin(r.data.user); } catch { setError('Could not sign in. Check the demo credentials.'); } }
  return <div className="login-page"><div className="login-card"><div className="brand">Velozity <span>Workspace</span></div><h1>Project dashboard</h1><p className="muted">Sign in to manage projects, tasks and team activity.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password"/></label>{error&&<div className="error">{error}</div>}<button className="primary">Sign in</button></form><div className="demo">Demo users: admin@velozity.local · ravi.pm@velozity.local · dev1@velozity.local<br/>Password: Password123!</div></div></div>
}

function App() {
  const [user,setUser]=useState<User|null>(null); const [activities,setActivities]=useState<Activity[]>([]); const [notifications,setNotifications]=useState<any[]>([]); const [unread,setUnread]=useState(0); const [presence,setPresence]=useState(0); const [socket,setSocket]=useState<Socket|null>(null);
  useEffect(()=>{ api.get('/auth/me').then(r=>setUser(r.data.user)).catch(()=>{}); },[]);
  useEffect(()=>{ if(!user) return; const s=io(socketUrl,{auth:{token:sessionStorage.getItem('accessToken')}}); setSocket(s); s.emit('activity:catchup'); s.on('activity:catchup',(items)=>setActivities(items)); s.on('activity:new',(item)=>setActivities(prev=>[...prev,item].slice(-20))); s.on('notification:new',(n)=>{setNotifications(prev=>[n,...prev]);setUnread(x=>x+1)}); s.on('presence:update',setPresence); api.get('/notifications').then(r=>{setNotifications(r.data.notifications);setUnread(r.data.unread)}); return ()=>{s.disconnect();setSocket(null)}; },[user]);
  if(!user) return <Login onLogin={setUser}/>;
  return <Dashboard user={user} activities={activities} notifications={notifications} unread={unread} setUnread={setUnread} presence={presence} socket={socket} onLogout={async()=>{await api.post('/auth/logout');setToken(null);setUser(null)}}/>;
}

function Dashboard({user,activities,notifications,unread,setUnread,presence,socket,onLogout}:{user:User;activities:Activity[];notifications:any[];unread:number;setUnread:(n:number)=>void;presence:number;socket:Socket|null;onLogout:()=>void}) {
 const [data,setData]=useState<any>(null); const [projects,setProjects]=useState<any[]>([]); const [selected,setSelected]=useState<string>(''); const [tasks,setTasks]=useState<Task[]>([]); const [filters,setFilters]=useState({status:'',priority:'',from:'',to:''}); const [showCreate,setShowCreate]=useState(false); const [showCreateProject,setShowCreateProject]=useState(false);
 const load=async()=>{ const [d,p]=await Promise.all([api.get('/dashboard'),api.get('/projects')]);setData(d.data);setProjects(p.data.projects); if(!selected&&p.data.projects[0])setSelected(p.data.projects[0].id); };
 useEffect(()=>{load()},[]); useEffect(()=>{ const params=new URLSearchParams(); if(selected) params.set('project',selected); Object.entries(filters).forEach(([k,v])=>{if(v)params.set(k,v)}); window.history.replaceState(null,'',`${window.location.pathname}?${params.toString()}`); },[selected,filters]); useEffect(()=>{if(!selected)return; const q=new URLSearchParams(Object.entries(filters).filter(([,v])=>v).map(([k,v])=>[k,v]));api.get(`/projects/${selected}?${q}`).then(r=>setTasks(r.data.tasks)).catch(()=>setTasks([]));},[selected,filters]);
 useEffect(()=>{if(!socket)return; const refresh=()=>load();socket.on('activity:new',refresh);socket.on('notification:new',refresh);return()=>{socket.off('activity:new',refresh);socket.off('notification:new',refresh)}},[socket]);
 async function status(id:number,status:string){await api.patch(`/projects/${selected}/tasks/${id}`,{status}); const r=await api.get(`/projects/${selected}`);setTasks(r.data.tasks)}
 async function read(id:string){await api.patch(`/notifications/${id}/read`);setUnread(Math.max(0,unread-1));}
 async function readAll(){await api.post('/notifications/read-all');setUnread(0)}
 const title=user.role==='ADMIN'?'Admin dashboard':user.role==='PM'?'Project manager dashboard':'Developer dashboard';
 return <div className="app"><aside><div className="brand">Velozity <span>Workspace</span></div><div className="userbox"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><small>{user.role==='PM'?'Project Manager':user.role}</small></div></div><nav><a className="active">Overview</a><a>Projects</a><a>Activity</a></nav><button className="logout" onClick={onLogout}>Sign out</button></aside><main><header><div><p className="eyebrow">Workspace</p><h1>{title}</h1></div><div className="header-actions"><span className="online"><i/> {presence} online</span><div className="bell" title="Notifications">🔔<b>{unread}</b><div className="notif-menu">{notifications.slice(0,5).map(n=><button key={n.id} className={n.read?'read':''} onClick={()=>read(n.id)}>{n.message}<small>{new Date(n.createdAt).toLocaleString()}</small></button>)}{notifications.length>0&&<button className="mark" onClick={readAll}>Mark all read</button>}</div></div></div></header>
 <section className="stats">{user.role==='ADMIN'?<><Stat label="Projects" value={data?.projects??'—'}/><Stat label="Overdue" value={data?.overdue??'—'}/><Stat label="Online now" value={presence}/><Stat label="Activities" value={activities.length}/></>:user.role==='PM'?<><Stat label="My projects" value={data?.projects?.length??'—'}/><Stat label="Open tasks" value={data?.tasks?.filter((t:any)=>t.status!=='DONE').length??'—'}/><Stat label="High priority" value={data?.tasks?.filter((t:any)=>['HIGH','CRITICAL'].includes(t.priority)).length??'—'}/></>:<><Stat label="Assigned" value={data?.tasks?.length??'—'}/><Stat label="In progress" value={data?.tasks?.filter((t:any)=>t.status==='IN_PROGRESS').length??'—'}/><Stat label="Overdue" value={data?.tasks?.filter((t:any)=>t.overdue).length??'—'}/></>}</section>
 <div className="grid"><section className="panel wide"><div className="panel-head"><div><h2>Tasks</h2><p>Filter the current project without changing the page.</p></div>{(user.role==='ADMIN'||user.role==='PM')&&<div className="button-row">{(user.role==='ADMIN'||user.role==='PM')&&<button className="secondary small" onClick={()=>setShowCreateProject(true)}>+ Project</button>} {(user.role==='ADMIN'||user.role==='PM')&&<button className="primary small" onClick={()=>setShowCreate(true)}>+ New task</button>}</div>}</div><div className="toolbar">{user.role!=='DEVELOPER'&&<select value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{Object.entries(labels).filter(([k])=>k.includes('TODO')||k.includes('PROGRESS')||k.includes('REVIEW')||k==='DONE').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}><option value="">All priorities</option>{['LOW','MEDIUM','HIGH','CRITICAL'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div><div className="task-list">{tasks.map(t=><div className="task" key={t.id}><div className="task-main"><div className="task-title">#{t.id} {t.title}</div><div className="task-meta">{t.developer?.name} · due {new Date(t.dueDate).toLocaleDateString()} {t.overdue&&<span className="overdue">Overdue</span>}</div></div><span className={`priority ${t.priority.toLowerCase()}`}>{labels[t.priority]}</span><select value={t.status} disabled={user.role==='DEVELOPER'&&t.developer.id!==user.id} onChange={e=>status(t.id,e.target.value)}>{['TODO','IN_PROGRESS','IN_REVIEW','DONE'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>)}{tasks.length===0&&<div className="empty">No tasks match these filters.</div>}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Live activity</h2><p>Last 20 events, delivered through WebSocket.</p></div><span className="live-dot">LIVE</span></div><div className="activity">{activities.slice(-20).reverse().map(a=><div className="activity-item" key={a.id}><span className="activity-icon">↗</span><div>{a.message}<small>{new Date(a.createdAt).toLocaleString()}</small></div></div>)}</div></section></div>
 {showCreate&&<CreateTask projectId={selected} onClose={()=>setShowCreate(false)} onCreated={()=>{setShowCreate(false);load();api.get(`/projects/${selected}`).then(r=>setTasks(r.data.tasks))}}/>} {showCreateProject&&<CreateProject onClose={()=>setShowCreateProject(false)} onCreated={(id)=>{setShowCreateProject(false);load().then(()=>setSelected(id))}}/>}
 </main></div>
}

function CreateProject({onClose,onCreated}:{onClose:()=>void;onCreated:(id:string)=>void}){
 const [clients,setClients]=useState<any[]>([]); const [form,setForm]=useState({name:'',description:'',clientId:''}); const [error,setError]=useState('');
 useEffect(()=>{api.get('/users/clients').then(r=>setClients(r.data.clients)).catch(()=>setError('Could not load clients.'))},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{const r=await api.post('/projects',form);onCreated(r.data.project.id)}catch(e){setError('Could not create the project. Check the selected client.')}}
 return <div className="modal"><form className="modal-card" onSubmit={submit}><div className="panel-head"><div><h2>New project</h2><p className="muted">Create a project for one of the existing clients.</p></div><button type="button" onClick={onClose}>×</button></div><label>Project name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Client<select required value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">Choose client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{error&&<div className="error">{error}</div>}<button className="primary">Create project</button></form></div>
}

function Stat({label,value}:{label:string;value:any}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function CreateTask({projectId,onClose,onCreated}:{projectId:string;onClose:()=>void;onCreated:()=>void}){const [devs,setDevs]=useState<any[]>([]);const [form,setForm]=useState({title:'',description:'',developerId:'',priority:'MEDIUM',dueDate:''});useEffect(()=>{api.get('/users/developers').then(r=>setDevs(r.data.users))},[]);async function submit(e:React.FormEvent){e.preventDefault();await api.post(`/projects/${projectId}/tasks`,form);onCreated()}return <div className="modal"><form className="modal-card" onSubmit={submit}><div className="panel-head"><h2>New task</h2><button type="button" onClick={onClose}>×</button></div><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Developer<select required value={form.developerId} onChange={e=>setForm({...form,developerId:e.target.value})}><option value="">Choose developer</option>{devs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="two"><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(x=><option key={x}>{x}</option>)}</select></label><label>Due date<input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></div><button className="primary">Create task</button></form></div>}
createRoot(document.getElementById('root')!).render(<App/>);
